//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comqueror.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HostComConnection_LastComPort {
            get {
                return ((string)(this["HostComConnection_LastComPort"]));
            }
            set {
                this["HostComConnection_LastComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int HostComConnection_LastBaudRate {
            get {
                return ((int)(this["HostComConnection_LastBaudRate"]));
            }
            set {
                this["HostComConnection_LastBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HostComConnection_LastParity {
            get {
                return ((string)(this["HostComConnection_LastParity"]));
            }
            set {
                this["HostComConnection_LastParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int HostComConnection_LastDataBits {
            get {
                return ((int)(this["HostComConnection_LastDataBits"]));
            }
            set {
                this["HostComConnection_LastDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HostComConnection_LastStoppBits {
            get {
                return ((string)(this["HostComConnection_LastStoppBits"]));
            }
            set {
                this["HostComConnection_LastStoppBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HostComConnection_LastHandshake {
            get {
                return ((string)(this["HostComConnection_LastHandshake"]));
            }
            set {
                this["HostComConnection_LastHandshake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceComConnection_LastComPort {
            get {
                return ((string)(this["DeviceComConnection_LastComPort"]));
            }
            set {
                this["DeviceComConnection_LastComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int DeviceComConnection_LastBaudRate {
            get {
                return ((int)(this["DeviceComConnection_LastBaudRate"]));
            }
            set {
                this["DeviceComConnection_LastBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceComConnection_LastParity {
            get {
                return ((string)(this["DeviceComConnection_LastParity"]));
            }
            set {
                this["DeviceComConnection_LastParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DeviceComConnection_LastDataBits {
            get {
                return ((int)(this["DeviceComConnection_LastDataBits"]));
            }
            set {
                this["DeviceComConnection_LastDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceComConnection_LastStoppBits {
            get {
                return ((string)(this["DeviceComConnection_LastStoppBits"]));
            }
            set {
                this["DeviceComConnection_LastStoppBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceComConnection_LastHandshake {
            get {
                return ((string)(this["DeviceComConnection_LastHandshake"]));
            }
            set {
                this["DeviceComConnection_LastHandshake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Log_UseStylisticSet {
            get {
                return ((bool)(this["Log_UseStylisticSet"]));
            }
            set {
                this["Log_UseStylisticSet"] = value;
            }
        }
    }
}
