//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comqueror.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comqueror.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Log ähnelt.
        /// </summary>
        public static string Button_ClearLog {
            get {
                return ResourceManager.GetString("Button_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect ähnelt.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send (CR/LF) ähnelt.
        /// </summary>
        public static string Button_Send_CR {
            get {
                return ResourceManager.GetString("Button_Send_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send (LF) ähnelt.
        /// </summary>
        public static string Button_Send_LF {
            get {
                return ResourceManager.GetString("Button_Send_LF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto scroll ähnelt.
        /// </summary>
        public static string CheckBox_AutoScroll {
            get {
                return ResourceManager.GetString("CheckBox_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        public static string Enum_ConnectionState_Connected {
            get {
                return ResourceManager.GetString("Enum_ConnectionState.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting... ähnelt.
        /// </summary>
        public static string Enum_ConnectionState_Connecting {
            get {
                return ResourceManager.GetString("Enum_ConnectionState.Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnected ähnelt.
        /// </summary>
        public static string Enum_ConnectionState_Disconnected {
            get {
                return ResourceManager.GetString("Enum_ConnectionState.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnecting... ähnelt.
        /// </summary>
        public static string Enum_ConnectionState_Disconnecting {
            get {
                return ResourceManager.GetString("Enum_ConnectionState.Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconnecting... ähnelt.
        /// </summary>
        public static string Enum_ConnectionState_Reconnecting {
            get {
                return ResourceManager.GetString("Enum_ConnectionState.Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string Enum_Handshake_None {
            get {
                return ResourceManager.GetString("Enum_Handshake.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RTS ähnelt.
        /// </summary>
        public static string Enum_Handshake_RequestToSend {
            get {
                return ResourceManager.GetString("Enum_Handshake.RequestToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RTS + XOn / XOff ähnelt.
        /// </summary>
        public static string Enum_Handshake_RequestToSendXOnXOff {
            get {
                return ResourceManager.GetString("Enum_Handshake.RequestToSendXOnXOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XOn / XOff ähnelt.
        /// </summary>
        public static string Enum_Handshake_XOnXOff {
            get {
                return ResourceManager.GetString("Enum_Handshake.XOnXOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ascii ähnelt.
        /// </summary>
        public static string Enum_MessageType_Ascii {
            get {
                return ResourceManager.GetString("Enum_MessageType.Ascii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hex ähnelt.
        /// </summary>
        public static string Enum_MessageType_Hex {
            get {
                return ResourceManager.GetString("Enum_MessageType.Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Even ähnelt.
        /// </summary>
        public static string Enum_Parity_Even {
            get {
                return ResourceManager.GetString("Enum_Parity.Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark (1) ähnelt.
        /// </summary>
        public static string Enum_Parity_Mark {
            get {
                return ResourceManager.GetString("Enum_Parity.Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string Enum_Parity_None {
            get {
                return ResourceManager.GetString("Enum_Parity.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Odd ähnelt.
        /// </summary>
        public static string Enum_Parity_Odd {
            get {
                return ResourceManager.GetString("Enum_Parity.Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space (0) ähnelt.
        /// </summary>
        public static string Enum_Parity_Space {
            get {
                return ResourceManager.GetString("Enum_Parity.Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string Enum_StopBits_None {
            get {
                return ResourceManager.GetString("Enum_StopBits.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        public static string Enum_StopBits_One {
            get {
                return ResourceManager.GetString("Enum_StopBits.One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.5 ähnelt.
        /// </summary>
        public static string Enum_StopBits_OnePointFive {
            get {
                return ResourceManager.GetString("Enum_StopBits.OnePointFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 ähnelt.
        /// </summary>
        public static string Enum_StopBits_Two {
            get {
                return ResourceManager.GetString("Enum_StopBits.Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A hex number must have two digits! ähnelt.
        /// </summary>
        public static string Error_HexNumberTooLong {
            get {
                return ResourceManager.GetString("Error_HexNumberTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is not a valid hex number! ähnelt.
        /// </summary>
        public static string Error_InvalidHexNumber {
            get {
                return ResourceManager.GetString("Error_InvalidHexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to connect to a com port before sending data. ähnelt.
        /// </summary>
        public static string Error_NotConnected {
            get {
                return ResourceManager.GetString("Error_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Baud ähnelt.
        /// </summary>
        public static string Format_Baud {
            get {
                return ResourceManager.GetString("Format_Baud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Connection ähnelt.
        /// </summary>
        public static string Group_Header_DeviceConnection {
            get {
                return ResourceManager.GetString("Group_Header_DeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ähnelt.
        /// </summary>
        public static string Group_Header_Messages {
            get {
                return ResourceManager.GetString("Group_Header_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PC / Host Connection ähnelt.
        /// </summary>
        public static string Group_Header_PcHostConnection {
            get {
                return ResourceManager.GetString("Group_Header_PcHostConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        public static string Group_Header_Send {
            get {
                return ResourceManager.GetString("Group_Header_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string Header_Column_Message {
            get {
                return ResourceManager.GetString("Header_Column_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source ähnelt.
        /// </summary>
        public static string Header_Column_Source {
            get {
                return ResourceManager.GetString("Header_Column_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More ähnelt.
        /// </summary>
        public static string Header_More {
            get {
                return ResourceManager.GetString("Header_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Append \r ähnelt.
        /// </summary>
        public static string Label_Append_CarriageReturn {
            get {
                return ResourceManager.GetString("Label_Append_CarriageReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Append \n ähnelt.
        /// </summary>
        public static string Label_Append_Newline {
            get {
                return ResourceManager.GetString("Label_Append_Newline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Baudrate: ähnelt.
        /// </summary>
        public static string Label_Baudrate {
            get {
                return ResourceManager.GetString("Label_Baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Databits: ähnelt.
        /// </summary>
        public static string Label_Databits {
            get {
                return ResourceManager.GetString("Label_Databits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handshake: ähnelt.
        /// </summary>
        public static string Label_Handshake {
            get {
                return ResourceManager.GetString("Label_Handshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message: ähnelt.
        /// </summary>
        public static string Label_Message {
            get {
                return ResourceManager.GetString("Label_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message type: ähnelt.
        /// </summary>
        public static string Label_MessageType {
            get {
                return ResourceManager.GetString("Label_MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parity: ähnelt.
        /// </summary>
        public static string Label_Parity {
            get {
                return ResourceManager.GetString("Label_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port: ähnelt.
        /// </summary>
        public static string Label_Port {
            get {
                return ResourceManager.GetString("Label_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Bits: ähnelt.
        /// </summary>
        public static string Label_StopBits {
            get {
                return ResourceManager.GetString("Label_StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comqueror ähnelt.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
